### ISSUE TITLE
Module can't be used in node

### ISSUE THREAD

**Issue by macdja38** [ScottyFillups/tumult#18]
As it is the use of import / export outside of .mjs files means that the package can't be run in node, which is a bit unfortunate as it would be great to be able to have the server and client side of my app able to generate the map. 

```
root@b9683822f7c3:/test# node --experimental-modules
> (node:44) ExperimentalWarning: The ESM module loader is experimental.
> const tumult = require('tumult');
Thrown:
/test/node_modules/tumult/index.js:1
(function (exports, require, module, __filename, __dirname) { import tumult from './lib'
                                                                     ^^^^^^
```

**Comment by ScottyFillups** [comment]
I'll look into it, thanks for bringing it up 😄 

If you're looking for a noise library that runs on Node.js, consider https://www.npmjs.com/package/fastnoisejs

If you find its documentation confusing, I'd appreciate some feedback

**Comment by ScottyFillups** [comment]
I'm guessing you're trying to make a voxel multiplayer server in Node.js?

**Comment by macdja38** [comment]
Yup, building this, https://game.ryke.xyz it was at a Hackathon so we had to move onto the next thing, ended up using simplex-noise instead. That said the documentation on wrapping perlin noise generators and changing the input arguments was very helpful and we did use that, thanks!

If we every have any problems scaling I'll definitely look into fastnoisejs, thanks for the recommendation.

**Comment by ScottyFillups** [comment]
Looks solid :+1: 

TBH for your hackathon, I think the main bottleneck will be the client-side rendering rather than the server. If you want to scale your server though, keep in mind that Node.js is single threaded, so you'll need to fork your application using child processes: https://medium.freecodecamp.org/node-js-child-processes-everything-you-need-to-know-e69498fe970a

**Comment by macdja38** [comment]
As far as client side rendering goes that's actually not a problem atm, we hit 30fps on an iPhone 5 and on anything newer it stays stable at the monitor fps.

Our character models right now are just rectangular cuboids so we have no problem rendering hundreds to thousands of those in one map. (though player update packets might prevent that)

As far as scaling yes, definitely more processes, though for terrain generation web-workers would probably not be a bad plan as you can move generating an entire chunk over to a different, and then in the future we can have the client generate the chunks and diff the default state of the chunk with the modified one and only send the changes to the chunk to each client.

Anyway, thanks for the advice!
