### ISSUE TITLE
What are the expected inputs

### ISSUE THREAD

**Issue by GMartigny** [ScottyFillups/tumult#27]
Hi,

I'm not familiar with the noises function and I find not quite clear in the documentation what are the expected inputs of exported functions.
In the usage example, you pass use `x` and `y` that are in the range `[0, 10]` and divide by an arbitrary `64`.
The same thing is true for the expected output of each functions. I don't know before extensive trial and error what is the expected range of the `.gen` function.
A good example of documentation can be found in large library like [lodash](https://lodash.com/docs).

With that said, either I'm doing things wrong, or some returned values are off.
[Here's a sample script](https://jsbin.com/qogacul/2/edit?html,js,output) trying to plot the returned values of `Simplex1`.
First, you can see a pattern emerging from the graph each time you rerun the script.
Secondly, the min and max values are `-0.158` and `0.158` for no apparent reasons.

**Comment by ScottyFillups** [comment]
Yeah, I'm sorry the library isn't very good; this is the first library I ever made and I wasn't a really good programmer at the time.

I didn't bother polishing it because I honestly never thought anyone would use it, lol :smile: 

I'll try making this better this weekend.

Basically the divisor of `x` and `y` determine the size of a "square" in pixels. Here's `x` and `y` divided by 32:

![image](https://user-images.githubusercontent.com/18666879/69969950-5f7b2f00-14eb-11ea-98ab-bb5aa0aa2bb2.png)

Here's `x` and `y` divided by 64:

![image](https://user-images.githubusercontent.com/18666879/69969978-6dc94b00-14eb-11ea-9197-d389a4131612.png)


Try playing around with this: http://scottyfillups.io/vizplex/

**Comment by GMartigny** [comment]
I'm just going to play around with noise, don't spend too much time rewriting this lib.

So, you're telling me `x` and `y` can have any positive value ?

And, what's up with the returned values ?

**Comment by ScottyFillups** [comment]
I'm telling you that successive `x` and `y` cannot increment by more than 1.

You can have something like 0.2, 0.4, 0.6, ..., but you can't have 1, 2, 3

The divisor is the "period" of the noise. Perlin noise is actually broken up as a grid. The length of each square is equal to the width. So, if you have a divisor of 1, you're trying to fit an entire square into a single pixel.

Also regarding the returned values, it should always be between `[-1, 1]`. If it's not, then there's a bug in my code.

Try playing around with this: https://scottyfillups.io/tumult/

**Comment by ScottyFillups** [comment]
Here's `n(x/2, y/2)`:

![image](https://user-images.githubusercontent.com/18666879/69982279-0d91d380-1502-11ea-8040-d47b61135606.png)

`n(x/4, y/4)`

![image](https://user-images.githubusercontent.com/18666879/69982317-27331b00-1502-11ea-9fa2-94342e36502b.png)

`n(x/8, y/8)`

![image](https://user-images.githubusercontent.com/18666879/69982332-387c2780-1502-11ea-9319-00556cbaf66a.png)


You can make some pretty cool stuff if you're creative. Here's

`sin(1/n(x/64,y/64))`

![image](https://user-images.githubusercontent.com/18666879/69982373-56498c80-1502-11ea-8ca6-5668e6986df5.png)

`sin(1/n(y/128,x/128)+ x*x)`

![image](https://user-images.githubusercontent.com/18666879/69982476-96a90a80-1502-11ea-9222-7939cfdb612a.png)

**Comment by GMartigny** [comment]
Ok thanks for the clarification, it helps a lot.
Also, consider [this plot](https://jsbin.com/qogacul/7/edit?html,js,output) showing a non-linear distribution and a output value in the `[-0.158, 0.158]` range.

**Comment by ScottyFillups** [comment]
Looked at your chart. I agree it's odd the range is only `[-0.158, 0.158]` for `1000` samples. I'll look into fixing up this library (and adding better documentation) after exams; there's just so much weird behaviour that it's awkward maintaining it.

**Comment by ScottyFillups** [comment]
Also, dunno what you're trying to do, but you might be interested in using the `.octavate` function:

1 octave:

![image](https://user-images.githubusercontent.com/18666879/70036368-a9fbba80-1582-11ea-9584-a2949ec47056.png)

2 octaves:

![image](https://user-images.githubusercontent.com/18666879/70036373-af590500-1582-11ea-919a-0edc01ea267c.png)

4 octaves:

![image](https://user-images.githubusercontent.com/18666879/70036416-c0097b00-1582-11ea-8a01-ad63dd8ed993.png)

Octavate is basically this function:

![image](https://user-images.githubusercontent.com/18666879/70038045-9d2c9600-1585-11ea-989b-3537dd6e2879.png)

Where

![image](https://user-images.githubusercontent.com/18666879/70039617-3c528d00-1588-11ea-837e-4d41d36ce1c9.png)


Here's an example where `p = 64`, `a = 3`:

```
n(x/64,y/64)*0.57 + n(x/32,y/32)*0.285 + n(x/16,y/16)*0.143
```

Notice how each successive term **halves** in period and "magnitude" (the coefficient). The **sum of all the coefficients is approximately 1**, which ensures that the sum of all noise functions is within the `[-1, 1]` range.
